touch "DataFile.txt"
echo " some new content to add......" >> "DataFile.txt"
echo "my name is Anjali Dubey.."
echo "grep in process.."
grep "Anj" "DataFile.txt"
echo "Hello world, Welcome to New Office"
sed 's/old_string/new_string/g' "DataFile.txt"
echo "awk is in proces to print line 2 and 3"
awk '{print $2, $1}' "DataFile.txt"
